AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A trimmed down template

Resources:
  MD5StrFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: md5str
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /md5str
            Method: GET
